log_level: debug
api_version: "1.0"
lang: js
server_url: http://demo.godspeed.systems
restaurant:
  base_url: restaurant.app.svc
delivery:
  base_url: delivery.app.svc
kafka1:
  client_id: orchestrator
  brokers: ["kafka:9092"]