log_level: debug
api_version: "1.0"
lang: js
# server_url: http://demo.godspeed.systems
restaurant:
  base_url: http://host.docker.internal:3002/
delivery:
  base_url: http://host.docker.internal:3000/
kafka1:
  client_id: orchestrator
  brokers: ["kafka:9092"]