name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: listing all directory
      run: |
          pwd
          ls

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: adminmindgrep/orchestrator
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Application Deployment
      run: |
          cd helm-chart
          helm template --dry-run . --set image.repository=adminmindgrep/orchestrator
          
#  helm install orchestrator . -n orchestrator --set image.repository=adminmindgrep/orchestrator