name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/values.yaml'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: listing all directory
      run: |
          pwd
          ls
          echo ${{ github.run_id }}
          
    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: adminmindgrep/orchestrator:${{ github.run_id }}
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'adminmindgrep/gs_service:dev'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'LOW,MEDIUM,CRITICAL,HIGH'          
        
    - name: Edit helm chart and push back to gitHub
      run: | 
          git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/Mindgreppers/orchestrator.git
          pwd
          cd orchestrator/helm-chart/
          OLD_TAG=`grep "tag: " values.yaml | awk '{print $2}'`
          sed -i "s/$OLD_TAG/'${{ github.run_id }}'/g" values.yaml
          git config user.name "Rishabh"
          git config user.email "rishabh@godspeed.systems"
          git add values.yaml
          git commit -m "Upgraded the orchestrator image tag to ${{ github.run_id }}"
          git push
